/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.alevicmar.finanzas;

import cl.alevicmar.tools.HR;

/**
 *
 * @author Janno
 */
public class IngresosHistoricos extends javax.swing.JFrame {

    /**
     * Creates new form IngresosHistoricos
     */
    public IngresosHistoricos() {
        initComponents();
        this.inicializar();
    }
    
    public void inicializar() {
        lblDesde.setVisible(false);
            txtFechaDesde.setVisible(false);
            lblHasta.setVisible(false);
            txtFechaHasta.setVisible(false);
            
            //foraneos
            chkPorFecha.setSelected(false);
            chkProductor.setSelected(false);
            
            txtRunProductor.setVisible(false);
            btnBuscarProductor.setVisible(false);
            chkTodos.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        chkTodos = new javax.swing.JCheckBox();
        chkPorFecha = new javax.swing.JCheckBox();
        lblDesde = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        txtFechaDesde = new com.toedter.calendar.JDateChooser();
        txtFechaHasta = new com.toedter.calendar.JDateChooser();
        chkProductor = new javax.swing.JCheckBox();
        txtRunProductor = new javax.swing.JTextField();
        btnBuscarProductor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finanzas de Ingresos Históricos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresos históricos"));

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaResultados);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        chkTodos.setSelected(true);
        chkTodos.setText("Todos");
        chkTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkTodosMouseClicked(evt);
            }
        });

        chkPorFecha.setText("por fecha");
        chkPorFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkPorFechaMouseClicked(evt);
            }
        });

        lblDesde.setText("desde");

        lblHasta.setText("hasta");

        txtFechaDesde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaDesdeFocusLost(evt);
            }
        });
        txtFechaDesde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFechaDesdePropertyChange(evt);
            }
        });

        chkProductor.setText("por Productor");
        chkProductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkProductorMouseClicked(evt);
            }
        });

        txtRunProductor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRunProductorFocusLost(evt);
            }
        });
        txtRunProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRunProductorActionPerformed(evt);
            }
        });
        txtRunProductor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRunProductorKeyTyped(evt);
            }
        });

        btnBuscarProductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/alevicmar/icons/find.png"))); // NOI18N
        btnBuscarProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 523, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTodos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkProductor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRunProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarProductor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkPorFecha)
                                .addGap(18, 18, 18)
                                .addComponent(lblDesde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHasta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkPorFecha)
                            .addComponent(lblDesde)))
                    .addComponent(lblHasta)
                    .addComponent(txtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProductor)
                    .addComponent(txtRunProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProductor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRunProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRunProductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRunProductorActionPerformed

    private void chkPorFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkPorFechaMouseClicked
        if(chkPorFecha.isSelected()) {
            //local elements
            lblDesde.setVisible(true);
            txtFechaDesde.setVisible(true);
            lblHasta.setVisible(true);
            txtFechaHasta.setVisible(true);
            
            //foraneos
            chkTodos.setSelected(false);
            chkProductor.setSelected(false);
            
            txtRunProductor.setVisible(false);
            btnBuscarProductor.setVisible(false);
        }else{
            //local elements
            lblDesde.setVisible(false);
            txtFechaDesde.setVisible(false);
            lblHasta.setVisible(false);
            txtFechaHasta.setVisible(false);
            
            //foraneos
            chkTodos.setSelected(true);
            chkProductor.setSelected(false);
            
            txtRunProductor.setVisible(false);
            btnBuscarProductor.setVisible(false);
        }
    }//GEN-LAST:event_chkPorFechaMouseClicked

    private void chkProductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkProductorMouseClicked
        if(chkProductor.isSelected()) {
            //local elements
            chkPorFecha.setSelected(false);
            lblDesde.setVisible(false);
            txtFechaDesde.setVisible(false);
            lblHasta.setVisible(false);
            txtFechaHasta.setVisible(false);
            
            //foraneos
            chkTodos.setSelected(false);
            
            txtRunProductor.setVisible(true);
            btnBuscarProductor.setVisible(true);
            HR.focus(txtRunProductor);
        }else{
            //local elements
            lblDesde.setVisible(false);
            txtFechaDesde.setVisible(false);
            lblHasta.setVisible(false);
            txtFechaHasta.setVisible(false);
            
            //foraneos
            chkTodos.setSelected(true);
            chkPorFecha.setSelected(false);
            
            txtRunProductor.setVisible(false);
            btnBuscarProductor.setVisible(false);
        }
    }//GEN-LAST:event_chkProductorMouseClicked

    private void chkTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkTodosMouseClicked
        if(chkTodos.isSelected()) {
            //desmarcar y ocultar todo
            lblDesde.setVisible(false);
            txtFechaDesde.setVisible(false);
            lblHasta.setVisible(false);
            txtFechaHasta.setVisible(false);
            
            //foraneos
            chkPorFecha.setSelected(false);
            chkProductor.setSelected(false);
            
            txtRunProductor.setVisible(false);
            btnBuscarProductor.setVisible(false);
        }else{
            lblDesde.setVisible(false);
            txtFechaDesde.setVisible(false);
            lblHasta.setVisible(false);
            txtFechaHasta.setVisible(false);
            
            //foraneos
            chkPorFecha.setSelected(false);
            chkProductor.setSelected(false);
            
            txtRunProductor.setVisible(false);
            btnBuscarProductor.setVisible(false);
            chkTodos.setSelected(true);
        }
    }//GEN-LAST:event_chkTodosMouseClicked

    private void txtRunProductorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRunProductorKeyTyped
        HR.largoMaximo(txtRunProductor, 12, evt);
        HR.ingresaCaracteresRut(evt);
    }//GEN-LAST:event_txtRunProductorKeyTyped

    private void txtRunProductorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRunProductorFocusLost
        if(!HR.contenido(txtRunProductor).isEmpty()) {
            if(HR.formatearYValidarRutCampo(txtRunProductor)) {
                btnBuscarProductorActionPerformed(null);
            }else{
                HR.insertarTexto(txtRunProductor, "");
                HR.focus(txtRunProductor);
            }
        }
    }//GEN-LAST:event_txtRunProductorFocusLost

    private void btnBuscarProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductorActionPerformed
        HR.mostrarMensaje("Exito.... ejeecutando webservice");
    }//GEN-LAST:event_btnBuscarProductorActionPerformed

    private void txtFechaDesdeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaDesdeFocusLost

    }//GEN-LAST:event_txtFechaDesdeFocusLost

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       this.dispose();
       System.gc();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtFechaDesdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFechaDesdePropertyChange
        txtFechaHasta.setMinSelectableDate(txtFechaDesde.getDate());
    }//GEN-LAST:event_txtFechaDesdePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresosHistoricos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresosHistoricos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresosHistoricos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresosHistoricos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresosHistoricos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProductor;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkPorFecha;
    private javax.swing.JCheckBox chkProductor;
    private javax.swing.JCheckBox chkTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JTable tablaResultados;
    private com.toedter.calendar.JDateChooser txtFechaDesde;
    private com.toedter.calendar.JDateChooser txtFechaHasta;
    private javax.swing.JTextField txtRunProductor;
    // End of variables declaration//GEN-END:variables
}
