/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.alevicmar.menuArchivo;

import cl.alevicmar.services.administrador.Administrador;
import cl.alevicmar.services.administrador.WebServiceAdministrador;
import java.awt.Component;

/**
 *
 * @author Victor Manuel Araya
 */
public class CambiarPassword extends javax.swing.JFrame {

    Component com                               = null;
    WebServiceAdministrador srvAdministrador    = null;
    Administrador user                          = null;
    
    public CambiarPassword() {
        initComponents();
        String mensaje = "<html><body><div width='260px' align='justify'><p style='font-size: 15px;'><b>Cambio de Contraseña</b></p><br />Si usted cambia la contraseña de su cuenta y la olvida tenga en cuenta que deberá ponerse en contacto con el equipo de Alevicmar para realizar las modificaciones pertinentes y asi recuperar el control de su cuenta. <br />Para cambiar la contraseña de su cuenta rellene los campos a continuación con la información solicitada.</div></body></html>";
        lblInstrucciones.setText(mensaje);
    }
    
    public CambiarPassword(Component com, WebServiceAdministrador srvAdministrador, Administrador user) {
        initComponents();
        this.com = com;
        this.srvAdministrador = srvAdministrador;
        this.user = user;
        String mensaje = "<html><body><div width='200px' align='justify'><p style='font-size: 15px;'><b>Terminal Bloqueado</b></p><br />El terminal de Feria Web Desktop Client se encuentra bloqueado. Para poder desbloquear utilice las credenciales del usuario que ha iniciado sesión en el sistema. Los datos del usuario con sesión activa se proporcionan a continuación:<br /><br /><b>usuario (<em>nombre del usuario</em>)</b><br /><br />Desbloquee la terminal con la contraseña de dicho usuario.</div></body></html>";
        lblInstrucciones.setText(mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambiar Contraseña");
        setResizable(false);

        lblInstrucciones.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstrucciones)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstrucciones)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblInstrucciones;
    // End of variables declaration//GEN-END:variables
}
