/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.alevicmar.menuArchivo;

import cl.alevicmar.main.Principal;
import cl.alevicmar.services.administrador.Administrador;
import cl.alevicmar.services.administrador.WebServiceAdministrador;
import cl.alevicmar.tools.HCorreo;
import cl.alevicmar.tools.HR;
import java.awt.Component;

/**
 *
 * @author Victor Manuel Araya
 */
public class Perfil extends javax.swing.JFrame {

    Component                   com                 = null;
    WebServiceAdministrador     srvAdministrador    = null;
    Administrador               user                = null;
    
    
    public Perfil() {
        initComponents();
    }
    
    public Perfil(Component com, WebServiceAdministrador srvAdministrador, Administrador user) {
        initComponents();
        this.setLocationRelativeTo(com);
        this.com = com;
        this.srvAdministrador = srvAdministrador;
        this.user = user;
        
        //rellenando campos
        HR.insertarTexto(txtNombres, user.getNombres());
        HR.desactivar(txtNombres);
        HR.insertarTexto(txtApaterno, user.getApaterno());
        HR.desactivar(txtApaterno);
        HR.insertarTexto(txtAmaterno, user.getAmaterno());
        HR.desactivar(txtAmaterno);
        HR.insertarTexto(txtEmail, user.getEmail());
        HR.desactivar(txtEmail);
        HR.insertarTexto(txtTelefono, user.getTelefono().trim());
        HR.desactivar(txtTelefono);
        HR.insertarTexto(txtCelular, user.getCelular().trim());
        HR.desactivar(txtCelular);
        HR.insertarTexto(txtFax, user.getFax().trim());
        HR.desactivar(txtFax);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAccion = new javax.swing.JButton();
        btnCambiarPassword = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApaterno = new javax.swing.JTextField();
        txtAmaterno = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perfil del Administrador");
        setResizable(false);

        jLabel1.setText("Nombres");

        btnAccion.setText("Cerrar");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        btnCambiarPassword.setText("Cambiar Contraseña");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("E-Mail");

        jLabel5.setText("Teléfono Fijo");

        jLabel6.setText("Celular");

        jLabel7.setText("Fax");

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        txtApaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApaternoKeyTyped(evt);
            }
        });

        txtAmaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmaternoKeyTyped(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        txtFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFaxKeyTyped(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/alevicmar/icons/pencil.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombres)
                                    .addComponent(txtApaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAmaterno)
                                    .addComponent(txtEmail)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtCelular)
                                    .addComponent(txtFax)))
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccion)
                    .addComponent(btnCambiarPassword))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        HR.insertarTexto(btnAccion, "Guardar");
        if(HR.contenido(btnEditar).compareToIgnoreCase("Editar") == 0) {
            HR.insertarTexto(btnEditar, "Cancelar");
            HR.insertarTexto(btnAccion, "Guardar");
            HR.activar(txtNombres);
            HR.activar(txtApaterno);
            HR.activar(txtAmaterno);
            HR.activar(txtEmail);
            HR.activar(txtTelefono);
            HR.activar(txtCelular);
            HR.activar(txtFax); 
            btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/alevicmar/icons/cross.png"))); 
        }else{
            HR.insertarTexto(btnEditar, "Editar");
            HR.insertarTexto(btnAccion, "Cerrar");
            btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/alevicmar/icons/pencil.png")));
            HR.desactivar(txtNombres);
            HR.desactivar(txtApaterno);
            HR.desactivar(txtAmaterno);
            HR.desactivar(txtEmail);
            HR.desactivar(txtTelefono);
            HR.desactivar(txtCelular);
            HR.desactivar(txtFax); 
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        HR.largoMaximo(txtNombres, 125, evt);
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApaternoKeyTyped
        HR.largoMaximo(txtApaterno, 75, evt);
    }//GEN-LAST:event_txtApaternoKeyTyped

    private void txtAmaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmaternoKeyTyped
        HR.largoMaximo(txtAmaterno, 75, evt);
    }//GEN-LAST:event_txtAmaternoKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        HR.largoMaximo(txtEmail, 255, evt);
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        HR.ingresaSoloNumeros(evt);
        HR.largoMaximo(txtTelefono, 12, evt);
        
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        HR.largoMaximo(txtCelular, 12, evt);
        HR.ingresaSoloNumeros(evt);
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtFaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxKeyTyped
        HR.largoMaximo(txtFax, 12, evt);
        HR.ingresaSoloNumeros(evt);
    }//GEN-LAST:event_txtFaxKeyTyped

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        if(HR.contenido(btnAccion).compareToIgnoreCase("cerrar") == 0) {
            this.dispose();
            System.gc();
        }else{
            //recuperando informacion
            String nombres      = HR.contenido(txtNombres);
            String apaterno     = HR.contenido(txtApaterno);
            String amaterno     = HR.contenido(txtAmaterno);
            String email        = HR.contenido(txtEmail);
            String telefono     = HR.contenido(txtTelefono);
            String celular      = HR.contenido(txtCelular);
            String fax          = HR.contenido(txtFax);
            
            if(nombres.trim().compareToIgnoreCase("") == 0) {
                HR.mostrarError("El campo de nombres está vacío");
                HR.focus(txtNombres);
            }else{
                if(apaterno.trim().compareToIgnoreCase("") == 0) {
                    HR.mostrarError("El campo de apellido paterno está vacío");
                    HR.focus(txtApaterno);
                }else{
                    if(amaterno.trim().compareToIgnoreCase("") == 0) {
                        HR.mostrarError("El campo de apellido materno está vacío");
                        HR.focus(txtAmaterno);
                    }else{
                        if(email.trim().compareToIgnoreCase("") == 0) {
                            HR.mostrarError("El campo de email está vacío");
                            HR.focus(txtEmail);
                        }else{
                            if(telefono.trim().compareToIgnoreCase("") == 0) {
                                HR.mostrarError("El campo de teléfono está vacío, si desea dejarlo vacío coloque un 0");
                                HR.focus(txtTelefono);
                                HR.insertarTexto(txtTelefono, "0");
                            }else{
                                if(celular.trim().compareToIgnoreCase("") == 0) {
                                    HR.mostrarError("El campo de celular está vacío, si desea dejarlo vacío coloque un 0");
                                    HR.focus(txtCelular);
                                    HR.insertarTexto(txtCelular, "0");
                                }else{
                                    if(fax.trim().compareToIgnoreCase("") == 0) {
                                        HR.mostrarError("El campo de fax está vacío, si desea dejarlo vacío coloque un 0");
                                        HR.focus(txtFax);
                                        HR.insertarTexto(txtFax, "0");
                                    }else{
                                        //respaldando usuario admin
                                        Administrador aux = user;
                                        //entregando nuevos valores
                                        user.setNombres(nombres);
                                        user.setApaterno(apaterno);
                                        user.setAmaterno(amaterno);
                                        user.setEmail(email);
                                        user.setTelefono(telefono);
                                        user.setCelular(celular);
                                        user.setFax(fax);

                                        if(srvAdministrador.getWebServiceAdministradorSoap().actualizaAdministrador(user)) {
                                            HR.mostrarMensaje("La información de perfil ha sido actualizada");
                                            ((Principal)com).setUser(user);
                                            ((Principal)com).setTitle("Feria Web Desktop Client - Conectado como: "+user.getUsuario()+"@feriaweb ("+user.getNombres()+" "+user.getApaterno()+" "+user.getAmaterno()+")");
                                            HR.insertarTexto(btnEditar, "Editar");
                                            HR.insertarTexto(btnAccion, "Cerrar");
                                            btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/alevicmar/icons/pencil.png")));
                                            HR.desactivar(txtNombres);
                                            HR.desactivar(txtApaterno);
                                            HR.desactivar(txtAmaterno);
                                            HR.desactivar(txtEmail);
                                            HR.desactivar(txtTelefono);
                                            HR.desactivar(txtCelular);
                                            HR.desactivar(txtFax); 
                                        }else{
                                            HR.mostrarError("La información de perfil no ha podido ser actualizada. Intentelo en otro momento");
                                            user = aux;
                                            HR.insertarTexto(btnAccion, "Cerrar");
                                            HR.insertarTexto(btnEditar, "Editar");
                                            btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/alevicmar/icons/pencil.png")));
                                            HR.desactivar(txtNombres);
                                            HR.desactivar(txtApaterno);
                                            HR.desactivar(txtAmaterno);
                                            HR.desactivar(txtEmail);
                                            HR.desactivar(txtTelefono);
                                            HR.desactivar(txtCelular);
                                            HR.desactivar(txtFax);
                                        }
 
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAccionActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(!HR.contenido(txtEmail).isEmpty()) {
            if(!HCorreo.validarEmail(HR.contenido(txtEmail))) {
                HR.mostrarError("El correo ingresado no es válido");
                HR.seleccionarTodo(txtEmail);
                HR.focus(txtEmail);
            }
        }
    }//GEN-LAST:event_txtEmailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnCambiarPassword;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAmaterno;
    private javax.swing.JTextField txtApaterno;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
