/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.alevicmar.menuAyuda;

import cl.alevicmar.main.Principal;
import java.awt.Component;
import javax.swing.UIManager;

/**
 *
 * @author Victor Manuel Araya
 */
public class AcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form AcercaDe
     */
    public AcercaDe() {
        initComponents();
        String mensaje = "<html><body><div width='330px' align='justify'><p style='font-size: 15px;'><b>Feria Web Desktop Client</b></p><hr>Plataforma de administración de escritorio multiplataforma de Feria Web Frutos Secos<br /><br />Esta aplicación esta diseñada para ser ejecutada en múltiples plataformas bajo una máquina virtual de Java. Si no dispone de Java puede descargarlo en <a href='https://www.java.com/es/download/'>java.com</a>.<hr>Proyecto desarrollado por Alevicmar Software Chile<br /><b>Victor Manuel Araya González<br />Alejandro Jesús Astroza Hermosilla<br />Marco Antonio Ramírez Bravo</b><br />Licencia para: Fundación Instituto Profesional Duoc UC<br /><br />&copy;2016 Todos los derechos reservados</div></body></html>";
        this.setLocationRelativeTo(null);
        lblInformacion.setText(mensaje);
    }
    
    public AcercaDe(Component componente) {
        initComponents();
        String mensaje = "<html><body><div width='330px' align='justify'><p style='font-size: 15px;'><b>Feria Web Desktop Client</b></p><hr>Plataforma de administración de escritorio multiplataforma de Feria Web Frutos Secos<br /><br />Esta aplicación esta diseñada para ser ejecutada en múltiples plataformas bajo una máquina virtual de Java. Si no dispone de Java puede descargarlo en <a href='https://www.java.com/es/download/'>java.com</a>.<hr>Proyecto desarrollado por Alevicmar Software Chile<br /><b>Victor Manuel Araya González<br />Alejandro Jesús Astroza Hermosilla<br />Marco Antonio Ramírez Bravo</b><br />Licencia para: Fundación Instituto Profesional Duoc UC<br /><br />&copy;2016 Todos los derechos reservados</div></body></html>";
        this.setLocationRelativeTo(componente);
        lblInformacion.setText(mensaje);
        if(componente instanceof Principal) {
            this.setIconImage(((Principal)componente).getIconImage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInformacion = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de Feria Web Desktop Client");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        lblInformacion.setText("jLabel1");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInformacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnAceptar)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcercaDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel lblInformacion;
    // End of variables declaration//GEN-END:variables
}
